services:
  - type: web
    name: chatapp-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.18.0
      - key: PORT
        fromService: 
          type: web
          name: chatapp-backend
          property: port